sudo: required
services: 
  - docker

before_install:
  - chmod +x Scripts/*.sh
  - docker pull uotbw/urho3d-build:debian-latest
#  - docker pull uotbw/urho3d-build:ubuntu-latest
#  - docker pull uotbw/urho3d-build:fedora-latest


language: c

script:
  - docker run -v /home/travis/build/urs-of-the-backwoods/HGamer3D/Scripts:/opt/scripts uotbw/urho3d-build:debian-latest bash -c "/opt/scripts/installHaskell.sh && /opt/scripts/getHGamer3D.sh && /opt/scripts/buildHGamer3D.sh"
#  - docker run -v /home/travis/build/urs-of-the-backwoods/HGamer3D/Scripts:/opt/scripts uotbw/urho3d-build:ubuntu-latest bash -c "/opt/scripts/installHaskell.sh && /opt/scripts/getHGamer3D.sh && /opt/scripts/buildHGamer3D.sh"
#  - docker run -v /home/travis/build/urs-of-the-backwoods/HGamer3D/Scripts:/opt/scripts uotbw/urho3d-build:fedora-latest bash -c "/opt/scripts/installHaskell.sh && /opt/scripts/getHGamer3D.sh && /opt/scripts/buildHGamer3D.sh"



