resolver: lts-8.20

flags:
  binary-serialise-cbor:
    newtime15: true

packages:
- location:
    git: https://github.com/well-typed/binary-serialise-cbor.git
    commit: c617075
- '../../../fresco/haskell-binding'
- '.'

extra-deps: ["vect-0.4.7"]

extra-lib-dirs:

